import type { FoodItem } from "@/lib/food-types";

/** Rozšírená lokálna databáza — bežné potraviny (SK / domáca strava). */
export const CORE_FOODS: FoodItem[] = [
  // ── Najčastejšie hľadané ──
  {
    id: "dried-tomatoes",
    name: "Sušené paradajky",
    kcalPer100: 258,
    kcalPerPiece: 21,
    unit: "ks",
    category: "Zelenina",
    keywords: [
      "sušené paradajky", "sušená paradajka", "dried tomato", "dried tomatoes",
      "sun-dried", "sun dried", "paradajky", "paradajka",
    ],
    proteinPerPiece: 1.3,
    fatPerPiece: 0.4,
    carbsPerPiece: 3.5,
    portionHints: [
      { label: "1 ks (~8g)", qty: 1 },
      { label: "4 ks", qty: 4 },
      { label: "10 ks", qty: 10 },
    ],
  },
  {
    id: "pesto",
    name: "Pesto (bazalkové)",
    kcalPer100: 410,
    kcalPerPiece: null,
    unit: "g",
    category: "Omáčky",
    keywords: [
      "pesto", "genovese", "pesto genovese", "bazalkové pesto", "basil pesto",
    ],
    proteinPer100: 5.0,
    fatPer100: 40,
    carbsPer100: 5.0,
    portionHints: [
      { label: "1 lyžička (5g)", qty: 5 },
      { label: "1 lyžica (15g)", qty: 15 },
      { label: "2 lyžice (30g)", qty: 30 },
    ],
  },
  {
    id: "dates",
    name: "Datle",
    kcalPer100: 282,
    kcalPerPiece: 23,
    unit: "ks",
    category: "Ovocie",
    keywords: ["datle", "dátľa", "datel", "datľa", "date", "dates", "ďaťla"],
    proteinPerPiece: 0.2,
    fatPerPiece: 0,
    carbsPerPiece: 6.0,
    portionHints: [
      { label: "1 ks (~8g)", qty: 1 },
      { label: "3 ks", qty: 3 },
      { label: "5 ks", qty: 5 },
    ],
  },
  {
    id: "rocket",
    name: "Rukola",
    kcalPer100: 25,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["rukola", "rocket", "arugula", "šalát"],
    proteinPer100: 2.6,
    fatPer100: 0.7,
    carbsPer100: 2.0,
    portionHints: [
      { label: "1 hrsť (30g)", qty: 30 },
      { label: "porcia (80g)", qty: 80 },
      { label: "balík (100g)", qty: 100 },
    ],
  },
  {
    id: "greek-cheese",
    name: "Feta syr",
    kcalPer100: 264,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["feta", "grécky syr", "feta cheese"],
    proteinPer100: 14,
    fatPer100: 21,
    carbsPer100: 4.1,
    portionHints: [
      { label: "1 kocka (20g)", qty: 20 },
      { label: "porcia (50g)", qty: 50 },
    ],
  },
  // Bielkoviny & vajcia
  {
    id: "egg",
    name: "Vajce",
    kcalPer100: null,
    kcalPerPiece: 78,
    unit: "ks",
    category: "Bielkoviny",
    keywords: ["vajce", "vajíčko", "egg", "eggs", "whole egg"],
    proteinPerPiece: 6.3,
    fatPerPiece: 5.3,
    carbsPerPiece: 0.6,
    portionHints: [
      { label: "1 ks", qty: 1 },
      { label: "2 ks", qty: 2 },
      { label: "3 ks", qty: 3 },
      { label: "4 ks", qty: 4 },
    ],
  },
  {
    id: "egg-white",
    name: "Bielok vajcia",
    kcalPer100: 52,
    kcalPerPiece: null,
    unit: "g",
    category: "Bielkoviny",
    keywords: ["bielok"],
    proteinPer100: 10.9,
    fatPer100: 0.2,
    carbsPer100: 1.0,
  },
  {
    id: "omelette-3",
    name: "Omeleta (3 vajcia)",
    kcalPer100: null,
    kcalPerPiece: 234,
    unit: "ks",
    category: "Jedlá",
    keywords: ["omeleta", "praženica"],
    proteinPerPiece: 19,
    fatPerPiece: 16,
    carbsPerPiece: 2,
  },
  {
    id: "tofu",
    name: "Tofu",
    kcalPer100: 76,
    kcalPerPiece: null,
    unit: "g",
    category: "Bielkoviny",
    keywords: ["tofu", "sója"],
    proteinPer100: 8.1,
    fatPer100: 4.2,
    carbsPer100: 1.9,
  },
  // Mliečne
  {
    id: "actimel",
    name: "Actimel",
    kcalPer100: null,
    kcalPerPiece: 77,
    unit: "ks",
    category: "Mliečne",
    keywords: ["actimel", "probiotic"],
    proteinPerPiece: 3.1,
    fatPerPiece: 1.4,
    carbsPerPiece: 11,
  },
  {
    id: "milk-15",
    name: "Mlieko 1,5 %",
    kcalPer100: 47,
    kcalPerPiece: null,
    unit: "ml",
    category: "Mliečne",
    keywords: ["mlieko", "milk"],
    proteinPer100: 3.4,
    fatPer100: 1.5,
    carbsPer100: 4.8,
  },
  {
    id: "milk-full",
    name: "Mlieko plnotučné",
    kcalPer100: 64,
    kcalPerPiece: null,
    unit: "ml",
    category: "Mliečne",
    keywords: ["mlieko"],
    proteinPer100: 3.3,
    fatPer100: 3.6,
    carbsPer100: 4.8,
  },
  {
    id: "yogurt-greek",
    name: "Grécky jogurt",
    kcalPer100: 97,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["jogurt", "grécky", "greek yogurt"],
    proteinPer100: 9.0,
    fatPer100: 5.0,
    carbsPer100: 4.0,
    portionHints: [
      { label: "malý pohár (150g)", qty: 150 },
      { label: "veľký pohár (200g)", qty: 200 },
    ],
  },
  {
    id: "yogurt-natural",
    name: "Jogurt prírodný",
    kcalPer100: 61,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["jogurt"],
    proteinPer100: 3.5,
    fatPer100: 3.3,
    carbsPer100: 4.7,
  },
  {
    id: "cottage-cheese",
    name: "Tvaroh",
    kcalPer100: 98,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["tvaroh"],
    proteinPer100: 12.5,
    fatPer100: 4.3,
    carbsPer100: 3.6,
  },
  {
    id: "cheese-eidam",
    name: "Syr eidam",
    kcalPer100: 357,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["syr", "eidam", "cheddar"],
    proteinPer100: 28,
    fatPer100: 26,
    carbsPer100: 0.5,
  },
  {
    id: "cheese-mozzarella",
    name: "Mozzarella",
    kcalPer100: 280,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["mozzarella", "syr"],
    proteinPer100: 22,
    fatPer100: 22,
    carbsPer100: 2.2,
  },
  {
    id: "butter",
    name: "Maslo",
    kcalPer100: 717,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["maslo", "butter"],
    proteinPer100: 0.9,
    fatPer100: 81,
    carbsPer100: 0.6,
  },
  // Mäso
  {
    id: "chicken-breast",
    name: "Kuracie prsia",
    kcalPer100: 165,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["kuracie", "prsia", "chicken"],
    proteinPer100: 31,
    fatPer100: 3.6,
    carbsPer100: 0,
  },
  {
    id: "chicken-thigh",
    name: "Kuracie stehno",
    kcalPer100: 209,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["kuracie", "stehno"],
    proteinPer100: 24,
    fatPer100: 13,
    carbsPer100: 0,
  },
  {
    id: "turkey",
    name: "Morčacie prsia",
    kcalPer100: 135,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["morčacie", "morka"],
    proteinPer100: 29,
    fatPer100: 1.0,
    carbsPer100: 0,
  },
  {
    id: "beef-lean",
    name: "Hovädzie libové",
    kcalPer100: 250,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["hovädzie", "beef"],
    proteinPer100: 26,
    fatPer100: 15,
    carbsPer100: 0,
  },
  {
    id: "pork-loin",
    name: "Bravčové karé",
    kcalPer100: 242,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["bravčové", "pork"],
    proteinPer100: 22,
    fatPer100: 15,
    carbsPer100: 0,
  },
  {
    id: "ham",
    name: "Šunka",
    kcalPer100: 145,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["šunka", "ham"],
    proteinPer100: 21,
    fatPer100: 5.5,
    carbsPer100: 1.0,
  },
  {
    id: "salami",
    name: "Saláma",
    kcalPer100: 336,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["saláma"],
    proteinPer100: 14,
    fatPer100: 29,
    carbsPer100: 2.0,
  },
  {
    id: "sausage",
    name: "Klobása",
    kcalPer100: 301,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["klobása"],
    proteinPer100: 13,
    fatPer100: 26,
    carbsPer100: 1.5,
  },
  // Ryby
  {
    id: "white-fish",
    name: "Biela ryba (treska)",
    kcalPer100: 90,
    kcalPerPiece: null,
    unit: "g",
    category: "Ryby",
    keywords: ["treska", "ryba", "fish"],
    proteinPer100: 18,
    fatPer100: 0.7,
    carbsPer100: 0,
  },
  {
    id: "salmon",
    name: "Losos",
    kcalPer100: 208,
    kcalPerPiece: null,
    unit: "g",
    category: "Ryby",
    keywords: ["losos", "salmon"],
    proteinPer100: 20,
    fatPer100: 13,
    carbsPer100: 0,
  },
  {
    id: "tuna-canned",
    name: "Tuniak v konzerve",
    kcalPer100: 116,
    kcalPerPiece: null,
    unit: "g",
    category: "Ryby",
    keywords: ["tuniak", "tuna"],
    proteinPer100: 25,
    fatPer100: 2.0,
    carbsPer100: 0,
  },
  // Zelenina
  {
    id: "spinach",
    name: "Špenát",
    kcalPer100: 23,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["špenát", "zelenina"],
    proteinPer100: 2.9,
    fatPer100: 0.4,
    carbsPer100: 1.4,
  },
  {
    id: "salad-mix",
    name: "Listový šalát",
    kcalPer100: 15,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["šalát", "rukola", "zelenina"],
    proteinPer100: 1.4,
    fatPer100: 0.2,
    carbsPer100: 1.8,
  },
  {
    id: "tomato",
    name: "Paradajka",
    kcalPer100: 18,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["paradajka", "rajčina"],
    proteinPer100: 0.9,
    fatPer100: 0.2,
    carbsPer100: 3.5,
  },
  {
    id: "cucumber",
    name: "Uhorka",
    kcalPer100: 15,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["uhorka"],
    proteinPer100: 0.7,
    fatPer100: 0.1,
    carbsPer100: 2.2,
  },
  {
    id: "pepper",
    name: "Paprika",
    kcalPer100: 31,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["paprika"],
    proteinPer100: 1.0,
    fatPer100: 0.3,
    carbsPer100: 6.0,
  },
  {
    id: "broccoli",
    name: "Brokolica",
    kcalPer100: 34,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["brokolica"],
    proteinPer100: 2.8,
    fatPer100: 0.4,
    carbsPer100: 4.7,
  },
  {
    id: "carrot",
    name: "Mrkva",
    kcalPer100: 41,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["mrkva"],
    proteinPer100: 0.9,
    fatPer100: 0.2,
    carbsPer100: 10,
  },
  {
    id: "zucchini",
    name: "Cuketa",
    kcalPer100: 20,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["cuketa"],
    proteinPer100: 1.2,
    fatPer100: 0.3,
    carbsPer100: 3.1,
  },
  {
    id: "green-beans",
    name: "Zelené fazuľky",
    kcalPer100: 35,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["fazuľky"],
    proteinPer100: 1.8,
    fatPer100: 0.1,
    carbsPer100: 7.0,
  },
  {
    id: "mushrooms",
    name: "Šampiňóny",
    kcalPer100: 22,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["šampiňóny", "huby"],
    proteinPer100: 3.1,
    fatPer100: 0.3,
    carbsPer100: 2.3,
  },
  {
    id: "onion",
    name: "Cibuľa",
    kcalPer100: 40,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["cibuľa"],
    proteinPer100: 1.1,
    fatPer100: 0.1,
    carbsPer100: 9.3,
  },
  {
    id: "potato",
    name: "Zemiak",
    kcalPer100: 77,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["zemiak", "zemiaky"],
    proteinPer100: 2.0,
    fatPer100: 0.1,
    carbsPer100: 17,
  },
  {
    id: "sweet-potato",
    name: "Batát",
    kcalPer100: 86,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["batát"],
    proteinPer100: 1.6,
    fatPer100: 0.1,
    carbsPer100: 20,
  },
  // Ovocie
  {
    id: "apple",
    name: "Jablko",
    kcalPer100: 52,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["jablko", "apple"],
    proteinPer100: 0.3,
    fatPer100: 0.2,
    carbsPer100: 14,
  },
  {
    id: "banana",
    name: "Banán",
    kcalPer100: 89,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["banán", "banana"],
    proteinPer100: 1.1,
    fatPer100: 0.3,
    carbsPer100: 23,
  },
  {
    id: "orange",
    name: "Pomaranč",
    kcalPer100: 47,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["pomaranč", "citrus"],
    proteinPer100: 0.9,
    fatPer100: 0.1,
    carbsPer100: 12,
  },
  {
    id: "berries-mix",
    name: "Bobuľové ovocie",
    kcalPer100: 57,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["čučoriedky", "maliny", "jahody"],
    proteinPer100: 0.7,
    fatPer100: 0.3,
    carbsPer100: 14,
  },
  {
    id: "grapes",
    name: "Hrozno",
    kcalPer100: 69,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["hrozno"],
    proteinPer100: 0.7,
    fatPer100: 0.2,
    carbsPer100: 18,
  },
  // Obilniny & pečivo
  {
    id: "rice-white",
    name: "Ryža uvarená",
    kcalPer100: 130,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["ryža", "rice"],
    proteinPer100: 2.7,
    fatPer100: 0.3,
    carbsPer100: 28,
  },
  {
    id: "rice-brown",
    name: "Hnedá ryža uvarená",
    kcalPer100: 123,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["ryža", "hnedá"],
    proteinPer100: 2.6,
    fatPer100: 0.9,
    carbsPer100: 26,
  },
  {
    id: "pasta",
    name: "Cestoviny uvarené",
    kcalPer100: 131,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["cestoviny", "špagety", "pasta"],
    proteinPer100: 5.0,
    fatPer100: 1.1,
    carbsPer100: 25,
  },
  {
    id: "oats",
    name: "Ovsené vločky",
    kcalPer100: 389,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["ovesné", "vločky", "oats", "oatmeal"],
    proteinPer100: 13,
    fatPer100: 7.0,
    carbsPer100: 66,
    portionHints: [
      { label: "1 porcia (40g)", qty: 40 },
      { label: "väčšia porcia (70g)", qty: 70 },
    ],
  },
  {
    id: "bread-white",
    name: "Chlieb biely",
    kcalPer100: 265,
    kcalPerPiece: null,
    unit: "g",
    category: "Pečivo",
    keywords: ["chlieb", "bread"],
    proteinPer100: 9.0,
    fatPer100: 3.2,
    carbsPer100: 49,
  },
  {
    id: "bread-whole",
    name: "Chlieb celozrnný",
    kcalPer100: 247,
    kcalPerPiece: null,
    unit: "g",
    category: "Pečivo",
    keywords: ["chlieb", "celozrnný"],
    proteinPer100: 9.0,
    fatPer100: 3.4,
    carbsPer100: 44,
  },
  {
    id: "roll",
    name: "Rožka",
    kcalPer100: null,
    kcalPerPiece: 220,
    unit: "ks",
    category: "Pečivo",
    keywords: ["rožok", "žemľa"],
    proteinPerPiece: 7.0,
    fatPerPiece: 3.0,
    carbsPerPiece: 40,
  },
  {
    id: "tortilla",
    name: "Tortilla",
    kcalPer100: null,
    kcalPerPiece: 140,
    unit: "ks",
    category: "Pečivo",
    keywords: ["tortilla", "wrap"],
    proteinPerPiece: 4.0,
    fatPerPiece: 3.5,
    carbsPerPiece: 25,
  },
  // Strukoviny
  {
    id: "lentils",
    name: "Šošovica uvarená",
    kcalPer100: 116,
    kcalPerPiece: null,
    unit: "g",
    category: "Strukoviny",
    keywords: ["šošovica"],
    proteinPer100: 9.0,
    fatPer100: 0.4,
    carbsPer100: 20,
  },
  {
    id: "chickpeas",
    name: "Cícer uvarený",
    kcalPer100: 164,
    kcalPerPiece: null,
    unit: "g",
    category: "Strukoviny",
    keywords: ["cícer"],
    proteinPer100: 8.9,
    fatPer100: 2.6,
    carbsPer100: 27,
  },
  {
    id: "beans",
    name: "Fazuľa uvarená",
    kcalPer100: 127,
    kcalPerPiece: null,
    unit: "g",
    category: "Strukoviny",
    keywords: ["fazuľa"],
    proteinPer100: 8.7,
    fatPer100: 0.5,
    carbsPer100: 23,
  },
  // Tuky & orechy
  {
    id: "olive-oil",
    name: "Olivový olej",
    kcalPer100: 884,
    kcalPerPiece: null,
    unit: "ml",
    category: "Tuky",
    keywords: ["olej", "olivový", "olive oil"],
    proteinPer100: 0,
    fatPer100: 100,
    carbsPer100: 0,
    portionHints: [
      { label: "1 lyžička (5ml)", qty: 5 },
      { label: "1 lyžica (15ml)", qty: 15 },
      { label: "2 lyžice (30ml)", qty: 30 },
    ],
  },
  {
    id: "sunflower-oil",
    name: "Slnečnicový olej",
    kcalPer100: 884,
    kcalPerPiece: null,
    unit: "ml",
    category: "Tuky",
    keywords: ["olej", "slnečnicový", "sunflower oil"],
    proteinPer100: 0,
    fatPer100: 100,
    carbsPer100: 0,
    portionHints: [
      { label: "1 lyžička (5ml)", qty: 5 },
      { label: "1 lyžica (15ml)", qty: 15 },
    ],
  },
  {
    id: "walnuts",
    name: "Vlašské orechy",
    kcalPer100: 654,
    kcalPerPiece: null,
    unit: "g",
    category: "Orechy",
    keywords: ["orechy", "vlašské", "walnuts"],
    proteinPer100: 15,
    fatPer100: 65,
    carbsPer100: 14,
    portionHints: [
      { label: "1 hrsť (30g)", qty: 30 },
      { label: "2 hrste (60g)", qty: 60 },
    ],
  },
  {
    id: "almonds",
    name: "Mandle",
    kcalPer100: 579,
    kcalPerPiece: null,
    unit: "g",
    category: "Orechy",
    keywords: ["mandle", "mandľ", "almonds"],
    proteinPer100: 21,
    fatPer100: 50,
    carbsPer100: 22,
    portionHints: [
      { label: "1 hrsť (23g)", qty: 23 },
      { label: "2 hrste (46g)", qty: 46 },
    ],
  },
  {
    id: "peanut-butter",
    name: "Arašidové maslo",
    kcalPer100: 588,
    kcalPerPiece: null,
    unit: "g",
    category: "Orechy",
    keywords: ["arašidové", "maslo", "peanut butter"],
    proteinPer100: 25,
    fatPer100: 50,
    carbsPer100: 20,
    portionHints: [
      { label: "1 lyžička (10g)", qty: 10 },
      { label: "1 lyžica (20g)", qty: 20 },
      { label: "2 lyžice (40g)", qty: 40 },
    ],
  },
  {
    id: "avocado",
    name: "Avokádo",
    kcalPer100: 160,
    kcalPerPiece: null,
    unit: "g",
    category: "Tuky",
    keywords: ["avokádo", "avocado"],
    proteinPer100: 2.0,
    fatPer100: 15,
    carbsPer100: 9.0,
    portionHints: [
      { label: "½ ks (80g)", qty: 80 },
      { label: "1 ks (160g)", qty: 160 },
    ],
  },
  // Nápoje
  {
    id: "water",
    name: "Voda",
    kcalPer100: 0,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["voda"],
    proteinPer100: 0,
    fatPer100: 0,
    carbsPer100: 0,
  },
  {
    id: "coffee-black",
    name: "Káva čierna",
    kcalPer100: 2,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["káva", "coffee"],
    proteinPer100: 0.1,
    fatPer100: 0,
    carbsPer100: 0,
  },
  {
    id: "beer-05",
    name: "Pivo 0,5 l",
    kcalPer100: null,
    kcalPerPiece: 210,
    unit: "ks",
    category: "Nápoje",
    keywords: ["pivo", "beer"],
    proteinPerPiece: 1.7,
    fatPerPiece: 0,
    carbsPerPiece: 16,
  },
  {
    id: "wine-red",
    name: "Červené víno",
    kcalPer100: 85,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["víno", "wine"],
    proteinPer100: 0.1,
    fatPer100: 0,
    carbsPer100: 2.6,
  },
  {
    id: "cola",
    name: "Cola",
    kcalPer100: 42,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["cola", "coca"],
    proteinPer100: 0,
    fatPer100: 0,
    carbsPer100: 11,
  },
  {
    id: "protein-shake",
    name: "Proteínový shake",
    kcalPer100: null,
    kcalPerPiece: 120,
    unit: "ks",
    category: "Nápoje",
    keywords: ["proteín", "shake"],
    proteinPerPiece: 20,
    fatPerPiece: 2.5,
    carbsPerPiece: 5.0,
  },
  // Sladkosti & snacky
  {
    id: "chocolate-dark",
    name: "Čokoláda horká",
    kcalPer100: 546,
    kcalPerPiece: null,
    unit: "g",
    category: "Sladkosti",
    keywords: ["čokoláda", "chocolate", "dark chocolate"],
    proteinPer100: 5.5,
    fatPer100: 32,
    carbsPer100: 60,
    portionHints: [
      { label: "2 kúsky (10g)", qty: 10 },
      { label: "4 kúsky (20g)", qty: 20 },
      { label: "tabuľka (100g)", qty: 100 },
    ],
  },
  {
    id: "honey",
    name: "Med",
    kcalPer100: 304,
    kcalPerPiece: null,
    unit: "g",
    category: "Sladkosti",
    keywords: ["med", "honey"],
    proteinPer100: 0.3,
    fatPer100: 0,
    carbsPer100: 82,
    portionHints: [
      { label: "1 lyžička (7g)", qty: 7 },
      { label: "1 lyžica (21g)", qty: 21 },
    ],
  },
  {
    id: "protein-bar",
    name: "Proteínová tyčinka",
    kcalPer100: null,
    kcalPerPiece: 200,
    unit: "ks",
    category: "Sladkosti",
    keywords: ["tyčinka", "protein"],
    proteinPerPiece: 20,
    fatPerPiece: 6.0,
    carbsPerPiece: 20,
  },
  {
    id: "chips",
    name: "Chipsy",
    kcalPer100: 536,
    kcalPerPiece: null,
    unit: "g",
    category: "Sladkosti",
    keywords: ["chipsy", "snack", "crisps", "chips"],
    proteinPer100: 6.0,
    fatPer100: 35,
    carbsPer100: 53,
    portionHints: [
      { label: "malý sáčok (30g)", qty: 30 },
      { label: "stredný sáčok (75g)", qty: 75 },
      { label: "veľký sáčok (150g)", qty: 150 },
    ],
  },
  // Hotové jedlá
  {
    id: "pizza-slice",
    name: "Pizza (kus)",
    kcalPer100: null,
    kcalPerPiece: 285,
    unit: "ks",
    category: "Jedlá",
    keywords: ["pizza"],
    proteinPerPiece: 12,
    fatPerPiece: 10,
    carbsPerPiece: 35,
  },
  {
    id: "burger",
    name: "Burger",
    kcalPer100: null,
    kcalPerPiece: 540,
    unit: "ks",
    category: "Jedlá",
    keywords: ["burger", "hamburger"],
    proteinPerPiece: 28,
    fatPerPiece: 28,
    carbsPerPiece: 45,
  },
  {
    id: "soup-clear",
    name: "Vývar / polievka",
    kcalPer100: 36,
    kcalPerPiece: null,
    unit: "ml",
    category: "Jedlá",
    keywords: ["polievka", "vývar"],
    proteinPer100: 2.5,
    fatPer100: 1.5,
    carbsPer100: 2.0,
  },
  {
    id: "pho-bo-700",
    name: "Pho Bo — veľká porcia 700 ml (hovädzia, ryžové rezance)",
    kcalPer100: 100,
    kcalPerPiece: 700,
    unit: "ks",
    category: "Jedlá",
    keywords: [
      "pho",
      "pho bo",
      "phở",
      "hovädzia",
      "hovadzia",
      "rezance",
      "ryžové",
      "ryzove",
      "700",
      "velka",
      "polievka",
      "vietnam",
    ],
    proteinPerPiece: 40,
    fatPerPiece: 8.0,
    carbsPerPiece: 90,
  },
  {
    id: "pho-bowl",
    name: "Pho (štandardná miska ~500 ml)",
    kcalPer100: null,
    kcalPerPiece: 480,
    unit: "ks",
    category: "Jedlá",
    keywords: ["pho", "polievka", "vietnam", "rezance"],
    proteinPerPiece: 28,
    fatPerPiece: 6.0,
    carbsPerPiece: 65,
  },
  {
    id: "pho-instant",
    name: "Pho instantná polievka (uvarená porcia)",
    kcalPer100: null,
    kcalPerPiece: 380,
    unit: "ks",
    category: "Jedlá",
    keywords: ["pho", "instant", "sachet", "ramen"],
    proteinPerPiece: 10,
    fatPerPiece: 8.0,
    carbsPerPiece: 60,
  },
  {
    id: "pho-broth",
    name: "Pho vývar (bez rezancov)",
    kcalPer100: 45,
    kcalPerPiece: null,
    unit: "ml",
    category: "Jedlá",
    keywords: ["pho", "vyvar", "bouillon", "polievka"],
    proteinPer100: 3.5,
    fatPer100: 1.5,
    carbsPer100: 3.0,
  },
  {
    id: "rice-noodles-pho",
    name: "Ryžové rezance na pho (uvarené)",
    kcalPer100: 109,
    kcalPerPiece: null,
    unit: "g",
    category: "Jedlá",
    keywords: ["pho", "rezance", "ryžové", "noodles"],
    proteinPer100: 2.0,
    fatPer100: 0.2,
    carbsPer100: 25,
  },
  {
    id: "rice-chicken-bowl",
    name: "Miska ryža + kuracie",
    kcalPer100: null,
    kcalPerPiece: 450,
    unit: "ks",
    category: "Jedlá",
    keywords: ["miska", "obed"],
    proteinPerPiece: 30,
    fatPerPiece: 8.0,
    carbsPerPiece: 55,
  },
];
