import type { FoodItem } from "@/lib/food-types";

/** Rozšírená lokálna databáza — bežné potraviny (SK / domáca strava). */
export const CORE_FOODS: FoodItem[] = [
  // Bielkoviny & vajcia
  {
    id: "egg",
    name: "Vajce",
    kcalPer100: null,
    kcalPerPiece: 78,
    unit: "ks",
    category: "Bielkoviny",
    keywords: ["vajce", "vajíčko", "egg"],
  },
  {
    id: "egg-white",
    name: "Bielok vajcia",
    kcalPer100: 52,
    kcalPerPiece: null,
    unit: "g",
    category: "Bielkoviny",
    keywords: ["bielok"],
  },
  {
    id: "omelette-3",
    name: "Omeleta (3 vajcia)",
    kcalPer100: null,
    kcalPerPiece: 234,
    unit: "ks",
    category: "Jedlá",
    keywords: ["omeleta", "praženica"],
  },
  {
    id: "tofu",
    name: "Tofu",
    kcalPer100: 76,
    kcalPerPiece: null,
    unit: "g",
    category: "Bielkoviny",
    keywords: ["tofu", "sója"],
  },
  // Mliečne
  {
    id: "actimel",
    name: "Actimel",
    kcalPer100: null,
    kcalPerPiece: 77,
    unit: "ks",
    category: "Mliečne",
    keywords: ["actimel", "probiotic"],
  },
  {
    id: "milk-15",
    name: "Mlieko 1,5 %",
    kcalPer100: 47,
    kcalPerPiece: null,
    unit: "ml",
    category: "Mliečne",
    keywords: ["mlieko", "milk"],
  },
  {
    id: "milk-full",
    name: "Mlieko plnotučné",
    kcalPer100: 64,
    kcalPerPiece: null,
    unit: "ml",
    category: "Mliečne",
    keywords: ["mlieko"],
  },
  {
    id: "yogurt-greek",
    name: "Grécky jogurt",
    kcalPer100: 97,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["jogurt", "grécky"],
  },
  {
    id: "yogurt-natural",
    name: "Jogurt prírodný",
    kcalPer100: 61,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["jogurt"],
  },
  {
    id: "cottage-cheese",
    name: "Tvaroh",
    kcalPer100: 98,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["tvaroh"],
  },
  {
    id: "cheese-eidam",
    name: "Syr eidam",
    kcalPer100: 357,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["syr", "eidam", "cheddar"],
  },
  {
    id: "cheese-mozzarella",
    name: "Mozzarella",
    kcalPer100: 280,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["mozzarella", "syr"],
  },
  {
    id: "butter",
    name: "Maslo",
    kcalPer100: 717,
    kcalPerPiece: null,
    unit: "g",
    category: "Mliečne",
    keywords: ["maslo", "butter"],
  },
  // Mäso
  {
    id: "chicken-breast",
    name: "Kuracie prsia",
    kcalPer100: 165,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["kuracie", "prsia", "chicken"],
  },
  {
    id: "chicken-thigh",
    name: "Kuracie stehno",
    kcalPer100: 209,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["kuracie", "stehno"],
  },
  {
    id: "turkey",
    name: "Morčacie prsia",
    kcalPer100: 135,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["morčacie", "morka"],
  },
  {
    id: "beef-lean",
    name: "Hovädzie libové",
    kcalPer100: 250,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["hovädzie", "beef"],
  },
  {
    id: "pork-loin",
    name: "Bravčové karé",
    kcalPer100: 242,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["bravčové", "pork"],
  },
  {
    id: "ham",
    name: "Šunka",
    kcalPer100: 145,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["šunka", "ham"],
  },
  {
    id: "salami",
    name: "Saláma",
    kcalPer100: 336,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["saláma"],
  },
  {
    id: "sausage",
    name: "Klobása",
    kcalPer100: 301,
    kcalPerPiece: null,
    unit: "g",
    category: "Mäso",
    keywords: ["klobása"],
  },
  // Ryby
  {
    id: "white-fish",
    name: "Biela ryba (treska)",
    kcalPer100: 90,
    kcalPerPiece: null,
    unit: "g",
    category: "Ryby",
    keywords: ["treska", "ryba", "fish"],
  },
  {
    id: "salmon",
    name: "Losos",
    kcalPer100: 208,
    kcalPerPiece: null,
    unit: "g",
    category: "Ryby",
    keywords: ["losos", "salmon"],
  },
  {
    id: "tuna-canned",
    name: "Tuniak v konzerve",
    kcalPer100: 116,
    kcalPerPiece: null,
    unit: "g",
    category: "Ryby",
    keywords: ["tuniak", "tuna"],
  },
  // Zelenina
  {
    id: "spinach",
    name: "Špenát",
    kcalPer100: 23,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["špenát", "zelenina"],
  },
  {
    id: "salad-mix",
    name: "Listový šalát",
    kcalPer100: 15,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["šalát", "rukola", "zelenina"],
  },
  {
    id: "tomato",
    name: "Paradajka",
    kcalPer100: 18,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["paradajka", "rajčina"],
  },
  {
    id: "cucumber",
    name: "Uhorka",
    kcalPer100: 15,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["uhorka"],
  },
  {
    id: "pepper",
    name: "Paprika",
    kcalPer100: 31,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["paprika"],
  },
  {
    id: "broccoli",
    name: "Brokolica",
    kcalPer100: 34,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["brokolica"],
  },
  {
    id: "carrot",
    name: "Mrkva",
    kcalPer100: 41,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["mrkva"],
  },
  {
    id: "zucchini",
    name: "Cuketa",
    kcalPer100: 20,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["cuketa"],
  },
  {
    id: "green-beans",
    name: "Zelené fazuľky",
    kcalPer100: 35,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["fazuľky"],
  },
  {
    id: "mushrooms",
    name: "Šampiňóny",
    kcalPer100: 22,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["šampiňóny", "huby"],
  },
  {
    id: "onion",
    name: "Cibuľa",
    kcalPer100: 40,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["cibuľa"],
  },
  {
    id: "potato",
    name: "Zemiak",
    kcalPer100: 77,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["zemiak", "zemiaky"],
  },
  {
    id: "sweet-potato",
    name: "Batát",
    kcalPer100: 86,
    kcalPerPiece: null,
    unit: "g",
    category: "Zelenina",
    keywords: ["batát"],
  },
  // Ovocie
  {
    id: "apple",
    name: "Jablko",
    kcalPer100: 52,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["jablko", "apple"],
  },
  {
    id: "banana",
    name: "Banán",
    kcalPer100: 89,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["banán", "banana"],
  },
  {
    id: "orange",
    name: "Pomaranč",
    kcalPer100: 47,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["pomaranč", "citrus"],
  },
  {
    id: "berries-mix",
    name: "Bobuľové ovocie",
    kcalPer100: 57,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["čučoriedky", "maliny", "jahody"],
  },
  {
    id: "grapes",
    name: "Hrozno",
    kcalPer100: 69,
    kcalPerPiece: null,
    unit: "g",
    category: "Ovocie",
    keywords: ["hrozno"],
  },
  // Obilniny & pečivo
  {
    id: "rice-white",
    name: "Ryža uvarená",
    kcalPer100: 130,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["ryža", "rice"],
  },
  {
    id: "rice-brown",
    name: "Hnedá ryža uvarená",
    kcalPer100: 123,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["ryža", "hnedá"],
  },
  {
    id: "pasta",
    name: "Cestoviny uvarené",
    kcalPer100: 131,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["cestoviny", "špagety", "pasta"],
  },
  {
    id: "oats",
    name: "Ovsené vločky",
    kcalPer100: 389,
    kcalPerPiece: null,
    unit: "g",
    category: "Obilniny",
    keywords: ["ovesné", "vločky"],
  },
  {
    id: "bread-white",
    name: "Chlieb biely",
    kcalPer100: 265,
    kcalPerPiece: null,
    unit: "g",
    category: "Pečivo",
    keywords: ["chlieb", "bread"],
  },
  {
    id: "bread-whole",
    name: "Chlieb celozrnný",
    kcalPer100: 247,
    kcalPerPiece: null,
    unit: "g",
    category: "Pečivo",
    keywords: ["chlieb", "celozrnný"],
  },
  {
    id: "roll",
    name: "Rožka",
    kcalPer100: null,
    kcalPerPiece: 220,
    unit: "ks",
    category: "Pečivo",
    keywords: ["rožok", "žemľa"],
  },
  {
    id: "tortilla",
    name: "Tortilla",
    kcalPer100: null,
    kcalPerPiece: 140,
    unit: "ks",
    category: "Pečivo",
    keywords: ["tortilla", "wrap"],
  },
  // Strukoviny
  {
    id: "lentils",
    name: "Šošovica uvarená",
    kcalPer100: 116,
    kcalPerPiece: null,
    unit: "g",
    category: "Strukoviny",
    keywords: ["šošovica"],
  },
  {
    id: "chickpeas",
    name: "Cícer uvarený",
    kcalPer100: 164,
    kcalPerPiece: null,
    unit: "g",
    category: "Strukoviny",
    keywords: ["cícer"],
  },
  {
    id: "beans",
    name: "Fazuľa uvarená",
    kcalPer100: 127,
    kcalPerPiece: null,
    unit: "g",
    category: "Strukoviny",
    keywords: ["fazuľa"],
  },
  // Tuky & orechy
  {
    id: "olive-oil",
    name: "Olivový olej",
    kcalPer100: 884,
    kcalPerPiece: null,
    unit: "ml",
    category: "Tuky",
    keywords: ["olej", "olivový"],
  },
  {
    id: "sunflower-oil",
    name: "Slnečnicový olej",
    kcalPer100: 884,
    kcalPerPiece: null,
    unit: "ml",
    category: "Tuky",
    keywords: ["olej", "slnečnicový"],
  },
  {
    id: "walnuts",
    name: "Vlašské orechy",
    kcalPer100: 654,
    kcalPerPiece: null,
    unit: "g",
    category: "Orechy",
    keywords: ["orechy", "vlašské"],
  },
  {
    id: "almonds",
    name: "Mandle",
    kcalPer100: 579,
    kcalPerPiece: null,
    unit: "g",
    category: "Orechy",
    keywords: ["mandle", "mandľ"],
  },
  {
    id: "peanut-butter",
    name: "Arašidové maslo",
    kcalPer100: 588,
    kcalPerPiece: null,
    unit: "g",
    category: "Orechy",
    keywords: ["arašidové", "maslo"],
  },
  {
    id: "avocado",
    name: "Avokádo",
    kcalPer100: 160,
    kcalPerPiece: null,
    unit: "g",
    category: "Tuky",
    keywords: ["avokádo"],
  },
  // Nápoje
  {
    id: "water",
    name: "Voda",
    kcalPer100: 0,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["voda"],
  },
  {
    id: "coffee-black",
    name: "Káva čierna",
    kcalPer100: 2,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["káva", "coffee"],
  },
  {
    id: "beer-05",
    name: "Pivo 0,5 l",
    kcalPer100: null,
    kcalPerPiece: 210,
    unit: "ks",
    category: "Nápoje",
    keywords: ["pivo", "beer"],
  },
  {
    id: "wine-red",
    name: "Červené víno",
    kcalPer100: 85,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["víno", "wine"],
  },
  {
    id: "cola",
    name: "Cola",
    kcalPer100: 42,
    kcalPerPiece: null,
    unit: "ml",
    category: "Nápoje",
    keywords: ["cola", "coca"],
  },
  {
    id: "protein-shake",
    name: "Proteínový shake",
    kcalPer100: null,
    kcalPerPiece: 120,
    unit: "ks",
    category: "Nápoje",
    keywords: ["proteín", "shake"],
  },
  // Sladkosti & snacky
  {
    id: "chocolate-dark",
    name: "Čokoláda horká",
    kcalPer100: 546,
    kcalPerPiece: null,
    unit: "g",
    category: "Sladkosti",
    keywords: ["čokoláda", "chocolate"],
  },
  {
    id: "honey",
    name: "Med",
    kcalPer100: 304,
    kcalPerPiece: null,
    unit: "g",
    category: "Sladkosti",
    keywords: ["med", "honey"],
  },
  {
    id: "protein-bar",
    name: "Proteínová tyčinka",
    kcalPer100: null,
    kcalPerPiece: 200,
    unit: "ks",
    category: "Sladkosti",
    keywords: ["tyčinka", "protein"],
  },
  {
    id: "chips",
    name: "Chipsy",
    kcalPer100: 536,
    kcalPerPiece: null,
    unit: "g",
    category: "Sladkosti",
    keywords: ["chipsy", "snack"],
  },
  // Hotové jedlá
  {
    id: "pizza-slice",
    name: "Pizza (kus)",
    kcalPer100: null,
    kcalPerPiece: 285,
    unit: "ks",
    category: "Jedlá",
    keywords: ["pizza"],
  },
  {
    id: "burger",
    name: "Burger",
    kcalPer100: null,
    kcalPerPiece: 540,
    unit: "ks",
    category: "Jedlá",
    keywords: ["burger", "hamburger"],
  },
  {
    id: "soup-clear",
    name: "Vývar / polievka",
    kcalPer100: 36,
    kcalPerPiece: null,
    unit: "ml",
    category: "Jedlá",
    keywords: ["polievka", "vývar"],
  },
  {
    id: "pho-bo-700",
    name: "Pho Bo — veľká porcia 700 ml (hovädzia, ryžové rezance)",
    kcalPer100: 100,
    kcalPerPiece: 700,
    unit: "ks",
    category: "Jedlá",
    keywords: [
      "pho",
      "pho bo",
      "phở",
      "hovädzia",
      "hovadzia",
      "rezance",
      "ryžové",
      "ryzove",
      "700",
      "velka",
      "polievka",
      "vietnam",
    ],
  },
  {
    id: "pho-bowl",
    name: "Pho (štandardná miska ~500 ml)",
    kcalPer100: null,
    kcalPerPiece: 480,
    unit: "ks",
    category: "Jedlá",
    keywords: ["pho", "polievka", "vietnam", "rezance"],
  },
  {
    id: "pho-instant",
    name: "Pho instantná polievka (uvarená porcia)",
    kcalPer100: null,
    kcalPerPiece: 380,
    unit: "ks",
    category: "Jedlá",
    keywords: ["pho", "instant", "sachet", "ramen"],
  },
  {
    id: "pho-broth",
    name: "Pho vývar (bez rezancov)",
    kcalPer100: 45,
    kcalPerPiece: null,
    unit: "ml",
    category: "Jedlá",
    keywords: ["pho", "vyvar", "bouillon", "polievka"],
  },
  {
    id: "rice-noodles-pho",
    name: "Ryžové rezance na pho (uvarené)",
    kcalPer100: 109,
    kcalPerPiece: null,
    unit: "g",
    category: "Jedlá",
    keywords: ["pho", "rezance", "ryžové", "noodles"],
  },
  {
    id: "rice-chicken-bowl",
    name: "Miska ryža + kuracie",
    kcalPer100: null,
    kcalPerPiece: 450,
    unit: "ks",
    category: "Jedlá",
    keywords: ["miska", "obed"],
  },
];
